### ISSUE TITLE
compile errors

### ISSUE THREAD

**Issue by syskeyontop** [vakho10/Java-Keylogger#2]
idk what the error is i added both build paths still when i compile it. It gives me an error anyone have a solution to this
https://user-images.githubusercontent.com/80404481/110918814-96243400-8341-11eb-982d-2255bfaf6398.PNG

**Comment by vakho10** [comment]
Are you exporting JAR using Eclipse? 
Try building it using Maven and Maven Assembly Plugin as executable JAR.
I think I've included it in pom.xml, but I may be wrong.
Here's the link on how to do it: [https://stackoverflow.com/questions/574594/how-can-i-create-an-executable-jar-with-dependencies-using-maven](https://stackoverflow.com/questions/574594/how-can-i-create-an-executable-jar-with-dependencies-using-maven)
